version: "2"
services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile_haproxy
    command: "haproxy -d -f /usr/local/etc/haproxy/haproxy.cfg"
    depends_on:
      - api
    ports:
      - '80:80'
      - '9001:9001'
    volumes:
      - ./frontend/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  redis-cache:
    image: redis
    container_name: redis
    ports:
    - "6379:6379"

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile_python
    scale: 3
    volumes:
      - ./data/books.json:/home/books.json
      - ./backend/src:/home/src/
 
  backend-denver:
    build:
      context: ./backend-denver/
      dockerfile: Dockerfile_denver
    ports:
      - '5000:5000'
    volumes:
      - ./data/books.json:/home/books.json
      - ./backend-denver/src:/home/src/
