version: "2"
services:
  passerelle:
    build:
      context: ./passerelle/
      dockerfile: Dockerfile_haproxy
    command: "haproxy -d -f /usr/local/etc/haproxy/haproxy.cfg"
    depends_on:
      - api
    ports:
      - '80:80'
      - '9001:9001'
    volumes:
      - ./passerelle/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        #redis:
        #image: redis
        #container_name: redis
        #ports:
        #- "6379:6379"
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile_python
    scale: 3
    volumes:
      - ./data/books.json:/home/books.json
      - ./api/src:/home/src/
  api_denver:
    build:
      context: ./api_denver/
      dockerfile: Dockerfile_denver
    volumes:
      - ./data/books.json:/home/books.json
      - ./api_denver/src:/home/src/
